#!/usr/bin/env bash
# SessionStart hook: prepares the /watch skill (.claude/skills/watch) in
# Claude Code on the web. Cloud containers start fresh every session, so the
# binaries and the skill config have to be recreated each time.
set -euo pipefail

# Local sessions manage their own tooling.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

# yt-dlp: always upgrade — YouTube breaks old versions regularly.
pip install --quiet --upgrade yt-dlp >/dev/null 2>&1 || echo "/watch: yt-dlp install failed" >&2

# ffmpeg/ffprobe for frame extraction.
if ! command -v ffmpeg >/dev/null 2>&1 || ! command -v ffprobe >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y -qq ffmpeg >/dev/null 2>&1 \
    || { apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq ffmpeg >/dev/null 2>&1; } \
    || echo "/watch: ffmpeg install failed" >&2
fi

# Skill config: mark setup as done so /watch doesn't re-ask first-run
# questions in every new container. Whisper keys come from the environment
# (GROQ_API_KEY / OPENAI_API_KEY), never from this repo.
CONFIG_DIR="$HOME/.config/watch"
CONFIG_FILE="$CONFIG_DIR/.env"
if [ ! -f "$CONFIG_FILE" ]; then
  mkdir -p "$CONFIG_DIR"
  umask 077
  cat > "$CONFIG_FILE" <<'EOF'
# /watch config (generated by .claude/hooks/session-start.sh)
WATCH_DETAIL=balanced
SETUP_COMPLETE=true
EOF
  chmod 600 "$CONFIG_FILE"
fi

exit 0
